[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
test = "test/foundry"
cache_path = "cache"

[profile.default.optimizer]
enabled = true
runs = 200

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
